### ISSUE TITLE
Problem when entering invalid value in the Advance settings, if "As set in Advance mode" soring option is selected

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather-widgets#107]
1. Create some news
2. D&D feather news widget
3. Open sorting options in list settings and select "As set in Advance mode" 
4. In Advance->Model settings enter invalid sort option
5. Note that nothing happened in page editor
6. Publish and open page editor again
No news are shown.
In such case default option "Last Published" should be applied.

**Comment by NadezhdaPetrova** [comment]
Verify in feather's branch SortingOptionsFixes
