### ISSUE TITLE
Feather Search box: deactivating Search and Indexes module causes exception on frontend page and in backend

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather-widgets#110]
Steps to reproduce: 
1. create page
2. drag and drop Search box widget
3. open designer and select search index and results page
4. publish page
5. go to Sitefinity Administration > Modules & Services
6. deactivate Search and Indexes module
7. open page from step 1.
As a result: "Exception has been thrown by the target of an invocation." is displayed and widget's designer displays same error message, too
8. see toolbox and page templates' toolbox
As a result: Search box and Search results widgets are present
9. view page on frontend
As a result: "The configuration 'SearchConfig' is not registered"

**Comment by GeorgiMateev** [comment]
The two widgets now will disappear from the toolbox when the module is deactivated. If this is not happening, you have to uregister the widgets from the toolbox.config and then reinstall the Search module.

**Comment by GeorgiMateev** [comment]
Branches:
feather/searchBox
feather-widgets/searchResults
