### ISSUE TITLE
Search results sorting by Title doesn't work on the frontend

### ISSUE THREAD

**Issue by VenetaBogoeva** [Sitefinity/feather-widgets#113]
Steps to reproduce:
1. create page
2. drag and drop Search box widget
3. create second page 
4. drag and drop Search results widget
5. Edit search results widget and set sort by Title
6. publish and view page
7. search for some existing content

As a result: 0  search results  (actually there is content with the searched word)

**Comment by ElenaGaneva** [comment]
I have removed this options becase this functionality depends on non implemented feature in Sitefinity
