### ISSUE TITLE
Search results sorting by "New-modified first" doesn't work on the frontend

### ISSUE THREAD

**Issue by VenetaBogoeva** [Sitefinity/feather-widgets#114]
Steps to reproduce:
1. create page
2. drag and drop Search box widget
3. create second page 
4. drag and drop Search results widget
5. publish and view page
6. search for some existing content
7. edit existing content 
8. search for the content and set "New-modified first"

As a result: The result is not correct - last modified content should be the first, but is not

**Comment by GeorgiMateev** [comment]
The new-modified option is removed from the sorting dropdown.
