### ISSUE TITLE
css widget renders ">" as "&gt;" in output

### ISSUE THREAD

**Issue by bsimser** [Sitefinity/feather-widgets#1153]
The CSS widget is rendering wrong when entered directly in the widget.

Steps to reproduce:
1. Drop a CSS widget on a page
2. Enter CSS directly and create a style like "body > .container {}" or something
3. Publish the page
4. View the source of the page in a browser (any browser)

The CSS is put in the <head> and rendered like this:

<style type="text\css" media="all">
body &gt; .container {
}
</style>

**Comment by PepiIvanova** [comment]
Hi bsimser,

The reported issue is fixed in latest Feather release (v.1.2.220.1).

Best,
Pepi

**Comment by bsimser** [comment]
Thanks. I just built our system about a week ago and haven't updated to this version yet.
