### ISSUE TITLE
Document Selector: In content block in document properties screen "Done" label should be change to "Insert this document"

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather-widgets#1221]
Open content block and insert a document. In document properties dialog not that there is "Done" label. Note that in images and videos the same label appears as "Insert this image/video"

**Comment by georgieff** [comment]
Sitefinity/feather#2095 : )

**Comment by veliniv** [comment]
Error when trying to insert file/image/video
GET http://localhost:51648/Sitefinity_1_2_270_4/Frontend-Assembly/Telerik.Sitef…ontend/assets/dist/fonts/sf-icon-font.ttf?1ea92cc84714f98ca037a9c2dbbdf5cf

**Comment by georgieff** [comment]
Should be fixed now by
https://github.com/Sitefinity/feather/pull/2104
