### ISSUE TITLE
How to add custom styles to Content block's WYSIWYG editor?

### ISSUE THREAD

**Issue by Masahigo** [Sitefinity/feather-widgets#1240]
Hi,

We have a need for adding some custom styles to the Format dropdown in the new HTML editor used in Feather MVC Content blocks. 

It seems to be based on this Kendo editor
http://demos.telerik.com/kendo-ui/editor/styles

How can we configure this component?
![new wysiwyg editor for content blocks kendoeditor](https://cloud.githubusercontent.com/assets/9364649/8005703/b45aef38-0b95-11e5-8c23-03fc8a9cdf89.jpg)

**Comment by PepiIvanova** [comment]
Hi Masahigo ,

Here are the steps to achieve the required functionality:
1. Create a custom designer view for Content block as it's described in the following article: https://github.com/Sitefinity/feather/wiki/Create-a-custom-designer-view
2. In custom designer view set a custom template for html field: 

```html
@using Telerik.Sitefinity.Frontend.Mvc.Helpers

<div ng-show="isShared" class="alert alert-warning">
    <b>@Html.Resource("ThisContentIsShared")</b> @Html.Resource("SharedContentWarning")
</div>

<sf-html-field class="kendo-content-block" sf-model="properties.Content.PropertyValue" sf-template-url="/Mvc/Views/ContentBlock/sf-html-field.sf-cshtml"></sf-html-field>
```
3. In html field custom template add formatting tool as it's described in the following article: http://demos.telerik.com/kendo-ui/editor/styles

```html
<textarea id="editor" style="height: 340px;"
    kendo-editor ng-model="sfModel"
    k-encoded="false"
    k-stylesheets='["/Mvc/Views/ContentBlock/html-field.css"]',
    k-tools='[
    { name: "formatting", items: [
                    { text: "Highlight Error", value: ".hlError" },
                    { text: "Highlight OK", value: ".hlOK" },
                    { text: "Inline Code", value: ".inlineCode" }
                ] },
    "bold", "italic", "underline", "trikethrough",
    "justifyLeft", "justifyCenter", "justifyRight",
    "insertUnorderedList", "insertOrderedList", "indent", "outdent",
    {
        name: "createLink",
        template: "<a href=\"\" class=\"k-tool k-group-start\" ng-click=\"openLinkSelector()\"><span class=\"k-tool-icon k-createLink\"></span></a>"
    },
    "unlink",
    {
        name: "insertImage",
        template: "<a href=\"\" class=\"k-tool k-group-start\" ng-click=\"openImageSelector()\"><span class=\"k-tool-icon k-insertImage\"></span></a>"
    },
    {
        name: "insertFile",
        template: "<a href=\"\" class=\"k-tool k-group-start\" ng-click=\"openDocumentSelector()\"><span class=\"k-tool-icon k-insertFile\"></span></a>"
    },
    {
        name: "insertVideo",
        template: "<a href=\"\" class=\"k-button custom-tool\" title=\"@(Res.Get<ClientComponentsResources>().InsertVideo)\" ng-click=\"openVideoSelector()\"><span class=\"glyphicon glyphicon-facetime-video\"></span></a>"
    },
    "createTable", "addColumnLeft", "addColumnRight", "addRowAbove", "addRowBelow", "deleteRow", "deleteColumn",
    "cleanFormatting",
    {
        name: "fullscreen",
        template: "<a class=\"k-button js-custom-tool custom-tool\" title=\"Fullscreen\" ng-click=\"toggleFullScreen()\"><span class=\"js-fullScreen glyphicon\"></span></a>"
    },
    {
        name: "htmlView",
        template: "<button class=\"custom-tool k-button pull-right js-custom-tool\" ng-click=\"toggleHtmlView()\">\{\{htmlViewLabel\}\}</button>"
    }
    ]'>
</textarea>

<sf-link-selector-modal id="linkSelectorModal"></sf-link-selector-modal>

<div class="mediaPropertiesModal"
     template-url="{{mediaPropertiesDialog}}"
     modal
     size="normal"
     existing-scope="true"
     window-class="sf-designer-dlg sf-timespan-selector-dlg"
     dialog-controller="{{sfMediaPropertiesController}}">
</div>
```

Let us know if this helps,
Pepi

**Comment by Masahigo** [comment]
Thanks! We tried this approach first but the Content block widget's edit mode didn't function. It just blinked when trying to edit the content but there was no JavaScript errors or similar either.

We had the following structure (under MVC/Views/ContentBlock)
- DesignerView.Simple.cshtml
- DesignerView.Simple.json
- sf-html-field.sf-cshtml

and in json file

{
    "priority": 1,
    "components" : ["sf-html-field"]
}

Then we noticed there was already a default file (sf-html-field.sf-cshtml) under
ResourcePackage/client-components/fields/html-field/

and by editing this template file directly we were able to customize the paragraph styles for the new HTML editor.

I have one more question regarding adding paragraph styles this way: how can it be configured so that it also preserves the default paragraph styles? We need most of them as well.

**Comment by PepiIvanova** [comment]
Hi,

Have a look at Custom tools demo: http://demos.telerik.com/kendo-ui/editor/custom-tools. The following code concatenates the default and custom formatting options:

```html
{
	name: "formatting",
	items: [].concat(
		kendo.ui.editor.FormattingTool.prototype.options.items,
		[{ text: "Fieldset", value: "fieldset" }]
	)
}             
```
Hope this helps,
Pepi

**Comment by Masahigo** [comment]
Hi,

We are able to add the default paragraph styles like so
..
items: kendo.ui.editor.FormattingTool.prototype.options.items

or the custom ones like so
..
items: [{ text: "Fieldset", value: "fieldset" }]

But trying this 
..
{
  name: "formatting",
  items: [].concat(
   kendo.ui.editor.FormattingTool.prototype.options.items,
   [{ text: "Fieldset", value: "fieldset" }]
  )
}..

Throws this error
"TypeError: undefined has no properties"

and if we remove this concat wrapper
[].concat(..)

and use either the one or other it works. 

So we are still not able to preserve the default styles.

**Comment by PepiIvanova** [comment]
Hi,

The temporary workaround is to list all default options and then list custom options:
```html
{ name: "formatting", items: [
	{ text: "Paragraph", value: "p" },
	{ text: "Quotation", value: "blockquote" },
	{ text: "Heading 1", value: "h1" },
	{ text: "Heading 2", value: "h2" },
	{ text: "Heading 3", value: "h3" },
	{ text: "Heading 4", value: "h4" },
	{ text: "Heading 5", value: "h5" },
	{ text: "Heading 6", value: "h6" },
	{ text: "Fieldset", value: "fieldset" }
] }
```

It seems the previous solution does not work in Kendo UI v.2014.3.1119 that is used in Feather.

Best,
Pepi

**Comment by Masahigo** [comment]
Okay, thanks for the help!
