### ISSUE TITLE
User documentation for Subscribe form

### ISSUE THREAD

**Issue by PepiIvanova** [Sitefinity/feather-widgets#1277]
Sitefinity doc: http://docs.sitefinity.com/subscribe-form-widget

**Comment by PepiIvanova** [comment]
https://github.com/Sitefinity/feather-docs/wiki/MVC-Subscribe-form-widget

**Comment by ElenaGaneva** [comment]
https://docs.sitefinity.com/subscribe-form-widget-mvc
