### ISSUE TITLE
User documentation for Unsubscribe form

### ISSUE THREAD

**Issue by PepiIvanova** [Sitefinity/feather-widgets#1278]
Sitefinity doc: http://docs.sitefinity.com/unsubscribe-form-widget

**Comment by NadezhdaPetrova** [comment]
https://github.com/Sitefinity/feather-docs/wiki/MVC-Unsubscribe-Form-Widget

**Comment by ElenaGaneva** [comment]
https://docs.sitefinity.com/unsubscribe-form-widget-mvc
