### ISSUE TITLE
Css\Js Widget Description rendering is inconsistant

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather-widgets#1308]
![cssvsjswidget](https://cloud.githubusercontent.com/assets/1542376/8234394/abc77f58-15a9-11e5-9f65-3fccfc0fbf98.PNG)

Would be nice to keep them the same, either put the pre on the JS or maybe do a custom bootstrap wrapper of like "bg-info" on both

**Comment by ElenaGaneva** [comment]
Hi Steve,

Thank you for your feedback. We will add this to the backlog.

Regards,
Elena

**Comment by mariushm** [comment]
Hi Steve,

This was fixed in some of the previous releases, it now looks like this:

![image](https://cloud.githubusercontent.com/assets/7304488/8305805/13841e8e-19bb-11e5-9fa1-a7a3c01c816a.png)

Thanks for pointing out!

**Comment by sitefinitysteve** [comment]
...we are on the latest version.  Have you tried using the description field?

**Comment by mariushm** [comment]
Yes, Here's how it looks on my end:
![image](https://cloud.githubusercontent.com/assets/7304488/8305999/e2dc51c8-19bc-11e5-8393-6c971653dd63.png)

**Comment by sitefinitysteve** [comment]
Oh you know what you're right!  Live hasn't been updated to the latest version yet...couple weeks behind.

**Comment by mariushm** [comment]
Come on, you are using the old and slow version on live? I wouldn't expect that from you ;)

**Comment by sitefinitysteve** [comment]
...massive oauth update blocking it ;) ...SOOON
