### ISSUE TITLE
Breadcrumb: How to include dynamic item's detail view (item's title) in the path?

### ISSUE THREAD

**Issue by Masahigo** [Sitefinity/feather-widgets#1334]
Hi,

I'm using the new Breadcrumb widget and noticed it does not include dynamic item's title in the path when the detail view is opened

![breadcrumb - how to include path to currently opened dynamic item](https://cloud.githubusercontent.com/assets/9364649/8454257/bd8ff1d8-2004-11e5-8e25-e4467fdea532.jpg)

This seems to be the case regardless you use a built-in module (like the News module showcased in the screenshot) or a custom module.

There was no mention about this in the wiki article for the widget
https://github.com/Sitefinity/feather/wiki/MVC-breadcrumb-widget

The ShowCurrentPageInTheEnd property seems to affect only pages - not dynamic items.

Is it possible to somehow extend the widget to include the dynamic item's title in the path?

It would be great if the Model used by the widget's frontend template (Breadcrumb.cshtml) provided a property like "ShowCurrentItemInTheEnd" which you could check against in the view and then get the dynamic item's title from the node.ItemTitle for example.

**Comment by Masahigo** [comment]
I realized there was this property "AllowVirtualNodes". At least in forms based breadcrumb widget this enables the currently open dynamic item's title to be displayed in the breadcrumb. Therefore this (Model.AllowVirtualNodes) would correspond to this "ShowCurrentItemInTheEnd" property I suggested.

But how can one check whether the node has an virtual node and/or access this virtual node's title to render it in the view? I tested setting this property to True but it had no effect using the default resource package (Bootstrap) template.

![feather mvc breadcrumb settings](https://cloud.githubusercontent.com/assets/9364649/8476470/6302bfe0-20ca-11e5-9b53-f67f041165fe.jpg)

**Comment by djsmith** [comment]
Hi Masahigo,

Did you find a fix or workaround for this problem. It seems like Sitefinity hasn't fixed it yet :-(

Thanks.

**Comment by ElenaGaneva** [comment]
Hello Masahigo,

This is no longer reproducible with latest versions of Sitefinity 11.0+.

Regards,
Elena 

Please note that to contribute to this project you should submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.
