### ISSUE TITLE
Feather Search box: autocomplete does not work for Search box placed in page template based on Bootstrap or SemanticUI template

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather-widgets#147]
Steps to reproduce:
1. create page template based on Bootstrap or SemanticUI (check for Foundation template, too) (EDIT Georgi: the page template should be in hybrid mode)
2. drag and drop Search box widget on this page template
3. set up Search box widget - search index and results page
4. create page based on page template from step 1.
5. publish and view page
6. search
As a result: no autocomplete is fired

**Comment by GeorgiMateev** [comment]
The issue occurs only when the page template is in hybrid mode. In MVC only mode the autocomplete is displayed.

**Comment by GeorgiMateev** [comment]
the fix is located in branches:
feather/fix-search-hybrid
feather-packages/fix-search-hybrid
