### ISSUE TITLE
Single Page selector integration in Navigation designer

### ISSUE THREAD

**Issue by PepiIvanova** [Sitefinity/feather-widgets#150]
Add "All pages under particular page" option in Navigation designer. Use Single Page selector to select the page. 

Wireframes: 
http://ux.sitefinity.com/Sitefinity%20Feather/#p=navigation_widget
http://ux.sitefinity.com/Sitefinity%20Feather/#p=page_selectors

**Comment by Boyko-Karadzhov** [comment]
branch nav-page-selector-#150
