### ISSUE TITLE
Multi Page selector integration in Navigation designer

### ISSUE THREAD

**Issue by PepiIvanova** [Sitefinity/feather-widgets#151]
Add "Custom selection of pages..." option in Navigation designer. Use Multi Page selector to select pages.

Wireframes: 
http://ux.sitefinity.com/Sitefinity%20Feather/#p=navigation_widget
http://ux.sitefinity.com/Sitefinity%20Feather/#p=page_selectors

**Comment by Boyko-Karadzhov** [comment]
branch nav-multipage-selector-#151
