### ISSUE TITLE
Lists widget disappears on Details view page

### ISSUE THREAD

**Issue by VesselinVassilev** [Sitefinity/feather-widgets#1532]
In Hybrid mode create a new page, e.g. News.
D&D the News MVC widget on it. 
D&D the List MVC widget. Select a list to show. 

When you visit the master page, e.g. /news the List items are shown, but as soon as you click on a news item and go to its details view - then the List widget disappears. 

Handling the UnknownAction should do the trick.

**Comment by jonathanread** [comment]
Agree this issue still exists in pure and hybrid.

**Comment by ElenaGaneva** [comment]
Hello,

This is fixed in latest versions in 11.0+.

Regards,
Elena
