### ISSUE TITLE
Hide default text while media content loads into the selector

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather-widgets#1549]
Hide the select image dialog until the callback returns results, show loading icon instead

![image](https://cloud.githubusercontent.com/assets/1542376/10463375/4b0d96f6-71b2-11e5-928f-e4c24c540c5b.png)

Problem is it opens up and there's a long wait (5-10 seconds) where the user thinks there's no images or libraries.  I would only expect to see that text if there are no images to select.

**Comment by ElenaGaneva** [comment]
Hello Steve,

This issue is fixed with latest [Sitefinity 11.1](https://github.com/Sitefinity/feather/releases/tag/v.11.1.6800.0)

Regards,
Elena
