### ISSUE TITLE
Can't build project missing nuget packages in source

### ISSUE THREAD

**Issue by jonathanread** [Sitefinity/feather-widgets#1581]
Can't Reach http://feather-ci.cloudapp.net:8088/nuget/ Also can't locate this assembly in the general sitefinity nuget feed

Error   20  Unable to find version '1.4.360.0' of package 'Telerik.Sitefinity.Frontend'.    

Telerik.Sitefinity.Frontend.SocialShare
Error   21  The command ""C:\Users\jread\Documents\GitHub\feather-widgets.nuget\NuGet.exe" install "C:\Users\jread\Documents\GitHub\feather-widgets\Telerik.Sitefinity.Frontend.SocialShare\packages.config" -source "http://feather-ci.cloudapp.net:8088/nuget/;https://www.nuget.org/api/v2/;http://nuget.sitefinity.com/nuget/"  -NonInteractive -RequireConsent -solutionDir "C:\Users\jread\Documents\GitHub\feather-widgets\ " -NoCache" exited with code 1. Telerik.Sitefinity.Frontend.SocialShare

**Comment by ElenaGaneva** [comment]
Hello Jonathan,

I am closing this issue since it is no longer applicable. 

Thank you,
Elena
