### ISSUE TITLE
Navigation widget: levels dropdown - "All" value is cut in chrome and IE

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather-widgets#171]
1. Create a page and drag and drop navigation widget
2. Edit the designer and in Levels to include select "All"
3. Save and edit
4. As a result : the All value is not displayed correctly in the designer - http://screencast.com/t/eBcHwfsaOX

**Comment by dpanov** [comment]
Fixed in UX-fixes branch - https://github.com/sitefinity/feather-widgets/tree/UX-fixes
