### ISSUE TITLE
Navigation Widget > Custom selection of pages - selected tab is empty

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather-widgets#172]
1. Edit the navigation widget
2. Select custom selection of pages
3. Switch to selected tab
4. As a result: the selected tab is empty and no pages are displayed there

**Comment by PetyaRachina** [comment]
branch : nav-multipage-selector-#151

**Comment by Tihomir-Petrov** [comment]
I've tested the bug fix and it seems that the bug is fixed.

**Comment by Tihomir-Petrov** [comment]
The fix is merged to master branch so QA engineer should check it directly there.
