### ISSUE TITLE
Paragraph Text data type is short text not long text.

### ISSUE THREAD

**Issue by luke-barnett** [Sitefinity/feather-widgets#1725]
This causing the database model behind it to be limited to 255 characters. Which isn't much to work with for a long text input.

https://github.com/Sitefinity/feather-widgets/blob/master/Telerik.Sitefinity.Frontend.Forms/Mvc/Controllers/ParagraphTextFieldController.cs#L17

**Comment by ElenaGaneva** [comment]
Hello Luke, 

This issue seems to be fixed in latest versions in Sitefinity 11.0+ so I am closing this issue.

Regards,
Elena 

Please note that to contribute to this project you should submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.
