### ISSUE TITLE
BlogPost Doesn't set Summary as MetaDescription

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather-widgets#1854]
https://github.com/Sitefinity/feather-widgets/blob/master/Telerik.Sitefinity.Frontend.Blogs/Mvc/Controllers/BlogPostController.cs#L198

MetaDescription\Summary is an important SEO requirement...

**Comment by ElenaGaneva** [comment]
Hello Steve,

In latest [Sitefinity 11.1](https://www.progress.com/documentation/sitefinity-cms/configure-open-graph-properties-on-widget-level) we introduced new functionality for managing the meta data.

Regards,
Elena
