### ISSUE TITLE
Feather Content block: Toggle icon is smaller 

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather-widgets#186]
Branch: master
Steps to reproduce:
1. create page based on Sitefinity built-in templates (no Bootstrap, SemanticUI or Foundation)
2. drag and drop Content block widget
3. open desinger
4. see Toggle icon 
As a result: it is smaller than the rest of the icons (see screenshot)
![image](https://cloud.githubusercontent.com/assets/234207/5855497/a41e8700-a241-11e4-8064-2b146a05d785.png)

**Comment by JenPeleva** [comment]
branch UX-fixes,  feather-packages
