### ISSUE TITLE
LoginForm.LoginForm.cshtml uses hardcoded CDN url for jQuery.Validate

### ISSUE THREAD

**Issue by jbokkers** [Sitefinity/feather-widgets#1861]
This JS library should be resolved through ScriptRef to have site configuration determine CDN or local loading of this script.

```
@Html.Script("//ajax.aspnetcdn.com/ajax/jquery.validate/1.8.1/jquery.validate.js", "top", false)
```

https://github.com/Sitefinity/feather-widgets/blob/482caa6e2d46627bb177eb1987358c341b4986d2/Telerik.Sitefinity.Frontend.Identity/Mvc/Views/LoginForm/LoginForm.LoginForm.cshtml#L10

**Comment by ElenaGaneva** [comment]
Hello jbokkers,

This issue is fixed with latest [Sitefinity 11.1](https://github.com/Sitefinity/feather/releases/tag/v.11.1.6800.0)

Regards,
Elena
