### ISSUE TITLE
NavigationView.Horizontal.cshtml uses obsolete hardcoded bootstrap.js cdn url

### ISSUE THREAD

**Issue by jbokkers** [Sitefinity/feather-widgets#1862]
Horizontal view for navigation uses a hard-coded bootstrap url.

```
@Html.Script("http://netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js", "top", false)
```

If this file is a requirement, it should be part of ...frontend.dll or ...frontend.navigation.dll and it should be updated to reflect the latest used version `3.3.6` and not an old `3.0.3` version. 

https://github.com/jbokkers/feather-widgets/blob/master/Telerik.Sitefinity.Frontend.Navigation/Mvc/Views/Navigation/NavigationView.Horizontal.cshtml#L10

**Comment by ElenaGaneva** [comment]
Hello jbokkers,

This is fixed in latest versions of 11.0+.

Regards,
Elena
