### ISSUE TITLE
Feather Content block: remove Save, Cancel and Advanced settings buttons in full screen

### ISSUE THREAD

**Issue by mirinka** [Sitefinity/feather-widgets#189]
Steps to reproduce:
1. create page
2. drag and drop Content block widget
3. edit widget
4. click on Toggle button and switch to full screen
As a result: Save, Cancel and Advanced settings appear, but they should not be present according to UX requirements (see http://ux.sitefinity.com/Sitefinity%20Feather/#p=fullscreen)

**Comment by dzhenko** [comment]
html-editor-fullscreen-toggle-#189
