### ISSUE TITLE
Search results do not security trim when  Enable filtering search results by view permissions is enabled

### ISSUE THREAD

**Issue by nhadro** [Sitefinity/feather-widgets#1905]
Is the widget setup to trim search results by view permissions for the current user when the "Enable filtering search results by view perimisions" is enabled?

In my test it does not appear to be working and I'm wondering if it's an issue on my side or the way it was implemented.

**Comment by flamecrow** [comment]
Any update on this?

**Comment by sdimitrov89** [comment]
Fixed in Sitefinity 12.2.7222.0
