### ISSUE TITLE
Content Block: In html view all buttons should be visible, but disabled, except full screen

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather-widgets#192]
Open feather content block - > html view and note that it look in the following way:
http://screencast.com/t/afHBQj63

This is wrong, all buttons should be visible, but disables, except full screen. Only this button should be enabled.

**Comment by PepiIvanova** [comment]
In html mode all buttons (except toggle full screen) are hidden instead of disabled

**Comment by ElenaGaneva** [comment]
This is fixed in latest versions 11.0+
