### ISSUE TITLE
Searchbox widget - XSS vulnerability in search results

### ISSUE THREAD

**Issue by Redirod** [Sitefinity/feather-widgets#1930]
Here is the input we get in the searchbox view: 

`<input type="search" title="@Html.Resource("SearchInput")" placeholder="@Model.BackgroundHint" id="@Html.Raw(searchTextBoxId)" class="form-control" value="@Html.Raw(ViewBag.SearchQuery)"/>`

The '**_value="@Html.Raw(ViewBag.SearchQuery)"_** '  presents an xss vulnerability. 
This security issue allows writing query strings within the input field.

**Example**:
Create a page using this widget. open the page on firefox and add this to the input field: 

> _test" onclick="alert('hello xss vulnerability')" class=_

search and then click on the input field.

**Comment by dboyanov** [comment]
No longer valid. The value does not contain Html.Raw.
