### ISSUE TITLE
Feather 1.6.540.0 - Image and Video pickers don't display titles (error with bind-html) 

### ISSUE THREAD

**Issue by OndeVai** [Sitefinity/feather-widgets#1974]
The image and video pickers don't display the titles for the library folders or video/image "tiles".

I see a script error for "unsafe" in angular --usually because ngSanitize is not included when bind-html attribute is used. Screen attached.

![unsafe-sf-angular](https://cloud.githubusercontent.com/assets/1340647/19281562/08844310-8fa8-11e6-8ac9-3aaeeae2f755.png)

**Comment by ElenaGaneva** [comment]
Hi OndeVai,

This is no longer reproducible with latest versions of 11.0+
