### ISSUE TITLE
Dynamic Content Widget - overriding default detail and list views not in documentation

### ISSUE THREAD

**Issue by OndeVai** [Sitefinity/feather-widgets#1978]
There is nothing in the documentation for overriding **default** detail and list views. There is a specific naming standard for doing this and it should be documented.

**Comment by ElenaGaneva** [comment]
Hi OndeVai,

If you want to customize the whole detail and list templates used as a base for all dynamic widgets you should use this article:
https://www.progress.com/documentation/sitefinity-cms/modify-default-templates-used-in-all-dynamic-content-widgets-mvc 

If you want to modify how a field looks like in all dynamic widgets (for example data time) use this article:
https://www.progress.com/documentation/sitefinity-cms/modify-field-template-of-all-dynamic-content-item-widgets-mvc

If you want to customize the List or Details template for only one dynamic content type use this one:
https://www.progress.com/documentation/sitefinity-cms/modify-fields-of-a-single-dynamic-content-widget-mvc 

Regards,
Elena

Please note that to contribute to this project you should submit your request in our feedback portal (https://feedback.telerik.com/Project/153) with detailed description.
