### ISSUE TITLE
Link selector: Not a correct behavior if you position the mouse at the end of a link

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather-widgets#198]
1. Open Content Block - > Link Selector
2. Create a link via Web Address option
3. Position the mouse (cursor)  at the end of the text, which is a link
4. Open link selector again
Note that it appear like you want to edit the existing link, web address and text to display fields are filled
5. Press insert link and note that new link is created
This behavior is not consistent. 
6. Select all the text and open again Link Selector
Note that text to display field is showing some html and looks broken

**Comment by NadezhdaPetrova** [comment]
Bug #178 must be fixed first

**Comment by PepiIvanova** [comment]
Cannot reproduce
