### ISSUE TITLE
Link selector > Page from this site - test this link is not working

### ISSUE THREAD

**Issue by PetyaRachina** [Sitefinity/feather-widgets#199]
1.  Create page
2. Create another page with content block
3. Open the link selector in the content block
4. Select page from this site and select to test this link
As a result: the test this link is not working

**Comment by NadezhdaPetrova** [comment]
'Test this link' option is removed from the wireframes for pages and email:
http://ux.sitefinity.com/Sitefinity%20Feather/#p=page_from_this_site
http://ux.sitefinity.com/Sitefinity%20Feather/#p=email
