### ISSUE TITLE
Link Selector: Text to display field is visible when you select an image and open link selector

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather-widgets#201]
1. Add an image in the content block
2. Select this image and open link selector
Note that text to display field is visible ( it should be hidden in this case ) and is populated with some html text

**Comment by Boyko-Karadzhov** [comment]
branch in feather  link-selector-image-#201

**Comment by SlaveyaShtereva** [comment]
'Text to display' is not visible any more -ok.
Test this link is visible and is not looking fine.
http://screencast.com/t/UM3JGv2Dsup

**Comment by PepiIvanova** [comment]
Check scenario like this: <span>test</span>
