### ISSUE TITLE
Attributes are not quoted and escaped for Text fields in forms

### ISSUE THREAD

**Issue by rhullah** [Sitefinity/feather-widgets#2036]
Not including quotes around the attribute throws off proper HTML for things like regular expressions. Additionally, regular expressions are not escaped.  So if they have quotes in them it'll also throw off proper HTML.

Ref: Telerik.Sitefinity.Frontend.Forms/Mvc/Models/Fields/TextField/TextFieldModel.cs

**Comment by ElenaGaneva** [comment]
Hi,

This issue was fixed in Sitefinity 12.1.7124.0.

Regards,
Elena
