### ISSUE TITLE
Link Selector: Undefined is populated for "mailto" if you enter invalid Email address

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather-widgets#205]
1. Open content block -> link selector
2. Open mail option, enter invalid mail and text to display
Note that in the html the following is generated for 'a' tag:
href="mailto:undefined"
3. If you open the text for edit in link selector undefined is populated in the email field

**Comment by GeorgiMateev** [comment]
Now there is a message if the entered email is not valid and the Insert button is disabled.
