### ISSUE TITLE
Navigation widget options documentation

### ISSUE THREAD

**Issue by PepiIvanova** [Sitefinity/feather-widgets#209]
Document the newly added options for Navigation widget. The following article should be updated: https://github.com/Sitefinity/feather/wiki/Navigation-Widget

**Comment by Boyko-Karadzhov** [comment]
Review here: [https://github.com/Sitefinity/feather-docs/wiki/Navigation-Widget] (https://github.com/Sitefinity/feather-docs/wiki/Navigation-Widget)
