### ISSUE TITLE
News widget not filtering on category

### ISSUE THREAD

**Issue by canberranet** [Sitefinity/feather-widgets#27]
The functionality described here
https://github.com/Sitefinity/feather/wiki/How-to-implement-action-that-filters-by-category-or-tag
is only working on tags, not categories.

sitefinity 7.2.5310.0
feather 1.0.10.2

**Comment by Tihomir-Petrov** [comment]
I've reviewed the documentation article and as a result I've applied changes in the code snippets. So, I can confirm that this functionality work in Feather 1.1.30.1.
