### ISSUE TITLE
Search box - Implement default message

### ISSUE THREAD

**Issue by rlee2015** [Sitefinity/feather-widgets#427]
Search Box is missing to allow authors to enter the default search message (i.e. to support different languages)? 

The idea is the same function in www.sitefinity.com. (i.e. Type your keyword here). When users try to access search box, the default message will be removed. Otherwise, the default message will display.efault message

**Comment by dzhenko** [comment]
Hi rlee2015,

We managed to include this functionality in our latest release. You can find the complete release notes at **https://github.com/Sitefinity/feather/releases/tag/v.1.1.110.0**.

Kind regards,
Dzhenko Penev

**Comment by mariushm** [comment]
Please re-fix this for Bootstrap - the change was reverted when merging other changes.
