### ISSUE TITLE
Help creating a custom Widget using feather that display NewsITems... A bit like the News MVC

### ISSUE THREAD

**Issue by AlexandreRoba** [Sitefinity/feather-widgets#463]
I'm trying to create my own MVC Widget that display NewsItem but I'm having difficulties integrating it with the search widget. I checked The implementation of the News MVC Widget but I cannot see what you have done to hae yours working. 

Here is what have done:
1) I have created a Controller called HubNewsController. This controller Implements the IContentLocatableView which register this widget as a potential candidate to display news Items. My controller looks like:
namespace SitefinityWebApp.Mvc.Controllers
{
    [ControllerToolboxItem(Name = "HubNews", Title = "HubNews", SectionName = "Hub Building Bloks")]
    public class HubNewsController : Controller, IContentLocatableView
    {
        public ActionResult DisplayNews01(int year,int month,int day,string urlname)
        {
            return View("Index");
        }
        public ActionResult DisplayNews02(string urlName)
        {
            return View("Index");
        }
        public ActionResult DisplayNews03(NewsItem newsItem)
        {
            return View("Index");
        }
        public ActionResult Index()
        {
            return View();
        }
        [NonAction]
        public IEnumerable<IContentLocationInfo> GetLocations()
        {
            var location = new ContentLocationInfo()
            {
                ContentType = TypeResolutionService.ResolveType("Telerik.Sitefinity.News.Model.NewsItem"),
                Priority = ContentLocationPriority.Highest,
                ProviderName = NewsManager.GetDefaultProviderName()
            };
            
            yield return location;
        }
        public bool? DisableCanonicalUrlMetaTag
        {
            get { return _disableCanonicalUrlMEtaTag; }
            set { _disableCanonicalUrlMEtaTag = value; }
        }
        private bool? _disableCanonicalUrlMEtaTag = false;
    }

   
}

Nothing fancy so far. I can drag my controller to a page (lets call it "HubNews" with the matching url "HubNews". Then publish it. when I open the URL http://localhost:xxxxx/HubNews I can see my default action "Index" being called. (Make sense)

I can open the News module, click on a news to edit it. I can see on the list of pages that the news can be accessed from the following URL :http://localhost:xxxxx/HubNews/2015/03/03/News-22

Where 2015/03/03 is the date of the pubication and news-22 is the url element of my news published.

When I use the search module, I can see my news being listed ins hte serach result with the url http://localhost:xxxxx/HubNews/2015/03/03/News-22...

Ok that is perfect...:)

My question is when I click on this link. Nothing happens. I get sometime a blank page and sometime a 404 depending on the rebuild and the last change I made.... I tried to create couple of actions on my controller for this URL to match:
public ActionResult DisplayNews01(int year,int month,int day,string urlname)
public ActionResult DisplayNews02(string urlName)
public ActionResult DisplayNews03(NewsItem newsItem)

None of those methods are actually called by the routing.

My question what should I do for having an action that matches the generated URL?

Thanks for any help you could give me on this.﻿

**Comment by dzhenko** [comment]
Hi AlexandreRoba,

You need to have an action result called ***Details*** and accepting an item of the same type as the ContentLocationInfo - in your case an item of type ***Telerik.Sitefinity.News.Model.NewsItem***. This should solve your problem.

You may take a look at our documentation article about master/detail controller at **https://github.com/Sitefinity/feather/wiki/How-to-implement-a-Master-Detail-content-controller** .

Kind regards,
Dzhenko Penev
