### ISSUE TITLE
Search box - WCAG 2.0 Level A Issue: 1.1.1 Non-text Content

### ISSUE THREAD

**Issue by rlee2015** [Sitefinity/feather-widgets#504]
Search box widget - WCAG 2.0 Level A Issue: 1.1.1 Non-text Content
http://www.w3.org/TR/WCAG20/#text-equiv-all

Form inputs have associated text labels.

Here are the solution:
1. To add a new search widget label called &#39;SeachForLabel&#39; under Administration -&gt; Labels and messages. This will support multi-languages.
2. To add a HTML lable tag under \ResourcePackages\ &lt;FeatherPackage&gt;\MVC\Views\SearchBox\SearchBox.cshtml

&lt;div class=&quot;form-group&quot;&gt;
&lt;label for=&quot;@Html.Raw(searchTextBoxId)&quot; class=&quot;hidden&quot;&gt;@Html.Resource(&quot;SearchForLabel&quot;)&lt;/label&gt;
&lt;input type=&quot;search&quot; id=&quot;@Html.Raw(searchTextBoxId)&quot; class=&quot;form-control&quot; value=&quot;@Html.Raw(ViewBag.SearchQuery)&quot;/&gt;
&lt;/div&gt;

**Comment by JenPeleva** [comment]
Fixed by adding a title attribute to the input, that shouldn't have a label as per the following article: 

http://www.w3.org/TR/WCAG20-TECHS/H65.html
