### ISSUE TITLE
Content block: When edit content block - the following resource html-field.min.css is not found

### ISSUE THREAD

**Issue by VenetaBogoeva** [Sitefinity/feather-widgets#548]
When edit content block - the following resource html-field.min.css is not found (the issue is reproducible on virtual directory)

 GET http://localhost:33706/Frontend-Assembly/Telerik.Sitefinity.Frontend/assets/dist/css/html-field.min.css 404 (Not Found)

**Comment by NadezhdaPetrova** [comment]
Test it for the packages, too: /ResourcePackages/[PackageName]/assets/dist/css/styles.min.css is not found
