### ISSUE TITLE
Inline editing is not working on page based on Bootstrap, Foundation and Semantic template

### ISSUE THREAD

**Issue by VenetaBogoeva** [Sitefinity/feather-widgets#563]
1. Create a page based on Bootstrap ( or Foundation and Semantic) template
2. Drag and drop content block widget
3. Add some content adn publish the page
4. Try to edit the page via inline editing

Actual result is: You are not able to edit the page
This is reproducible only in IS . when try this with virutal directory it works

**Comment by ElenaGaneva** [comment]
Seems that now the page is rendered in different cotnext, so when ASP makes request ot get file for the MasterFilePath the inline editing is not allowed (because user is not backend in current cotnext)
Added some changes in Feather branch InlinEditingFixInPackages, still the issue persist
