### ISSUE TITLE
Profile: Entering invalid Old password is loading a wrong page content and a wrong message

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather-widgets#614]
1 . D&D Profile widget on a page
2. View this page, expand Change password section
3. Enter wrong old password 
4. Enter correct New password and Repeat new password 
5. Press save changes
Note the page is reloaded with the following message "Edit is not allowed!"
http://screencast.com/t/hBSQ04dv

**Comment by SlaveyaShtereva** [comment]
The same problem is valid when you enter an avatar with wrong extension and press Save

**Comment by NadezhdaPetrova** [comment]
<b>IMPORTANT:</b> The error message for bootstrap and semantic ui packages is not styled!

**Comment by NadezhdaPetrova** [comment]
Fixed in team7-bug-fixing branch
