### ISSUE TITLE
LoginForm: ForgotPassword not working

### ISSUE THREAD

**Issue by konstrui** [Sitefinity/feather-widgets#619]
After enabling the 'ForgotPassword' link I can enter my email address to allow Sitefinity to email me a Password Reset link. If I click on 'Send' I'm getting a 404 error and nothing happens.

I did setup the parameters on the membership provider.

Not sure what goes wrong.
![forgot](https://cloud.githubusercontent.com/assets/1482375/6754536/819e2ce0-cf1d-11e4-9585-f2e68f3ed4cf.png)
![error](https://cloud.githubusercontent.com/assets/1482375/6754538/84d61bc0-cf1d-11e4-8f6c-cc2e45ff6e90.png)

**Comment by konstrui** [comment]
This is the exception:

![exception](https://cloud.githubusercontent.com/assets/1482375/6754734/c0245024-cf1e-11e4-8008-2df78cc8e0e7.png)

**Comment by PepiIvanova** [comment]
We cannot reproduce the described issue locally. What version of Feather are you using? We used to have a similar issue (https://github.com/Sitefinity/feather/issues/961) but it was fixed for version 1.2.120.0.

Best,
Pepi

**Comment by konstrui** [comment]
I use the latest version with Sitefinity 8.

--
Dit bericht is verstuurd vanaf mijn telefoon en is om die reden kort en direct.

Op 21 mrt. 2015 om 11:15 heeft PepiIvanova <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


We cannot reproduce the described issue locally. What version of Feather are you using? We used to have a similar issue (Sitefinity/feather#961<https://github.com/Sitefinity/feather/issues/961>) but it was fixed for version 1.2.120.0.

Best,
Pepi

-

**Comment by PepiIvanova** [comment]
Could you give us exact steps that you perform in order to reproduce the issue, so we could try to reproduce it on our side:
1. Advanced settings related to Forgot Password functionality
2. Login form widget settings
3. Could you try to reproduce the issue on a blank page?

Best,
Pepi

**Comment by konstrui** [comment]
I will try it on a new project and let you know the outcome. Although I see a new bug has added for the next milestone?

**Comment by PepiIvanova** [comment]
The newly logged bug is for a different scenario - 404 is thrown when you try to reset your password on Bootstrap, Foundation and SemanticUI templates (it works on hybrid template).
According to the screenshots you are receiving 404 several steps earlier when try to send the email.

**Comment by konstrui** [comment]
OK, I see.
What is the difference between **AllowResetPassword** and **EnablePasswordReset**? I can think of something, but it maybe is a bit vague?

**Comment by konstrui** [comment]
This is what I tested with a new installation:
* Sitefinity 8.0.5701

**Comment by konstrui** [comment]
This is what I tested so far:

* Sitefinity 8.0.5701
* Feather 1.2.130.0

Created a new project. New homepage and dragged the LoginForm to the page.
* See screenshot for the simple settings: loginform-simple
* See screenshot for the advanced settings: loginform-advanced

![loginform-simple](https://cloud.githubusercontent.com/assets/1482375/6765821/1332b5ae-cff0-11e4-8388-ee1b0749d412.png)
![loginform-advanced](https://cloud.githubusercontent.com/assets/1482375/6765822/17e9c948-cff0-11e4-91ad-4bf0598b1a6a.png)

I did not get the 404 error anymore as within my other project, but now inside the URL it gave me this error message:

    http://localhost/feathertest/home/ForgotPassword?emailSent=False&email=mail%40konstrui.nl&emailNotFound=False&error=Exception+has+been+thrown+by+the+target+of+an+invocation.

Looking in the log file I can see it looks for a Notification Profile, so I also configured this.
After this the email was sent correct.

However, in my existing project this is still not working, also not with the latest Feather release. It gives me a 404 error page. like before.

**Comment by konstrui** [comment]
I also created a new page without a template in the same project that is causing troubles. Then the ResetPassword works, so I'm wondering if there is any javascript that is required for the LoginForm to work?

On the page where the widget doesn't work, it immediately redirects to a new page, as if there is something wrong with the routing. It doesn't generates an error either.

**Comment by konstrui** [comment]
Any idea on how we can test this? I can't get this to work on an existing project.

**Comment by PepiIvanova** [comment]
Most probably the issue is caused by something (control or script) on your template. So could try to isolate the problem by removing the controls one by one from the template?
Let us know if you have any progress.
