### ISSUE TITLE
Provider selector in News/Image Gallery/Dynamic modules is not looking fine

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather-widgets#628]
Set more than one provider for News/Image Gallery/Dynamic modules 
Open the widget for edit
Note that dropdown for provider selector is not looking fine:
http://screencast.com/t/krYF47vv

**Comment by mirinka** [comment]
Reop: reproducible for List and Document list widget, too

**Comment by mirinka** [comment]
Content block > More > Use shared, too
