### ISSUE TITLE
Link Selector: Incorrect html is generated after editing a link in Firefox

### ISSUE THREAD

**Issue by SlaveyaShtereva** [Sitefinity/feather-widgets#674]
Firefox issue:
1. Open content block and create a link from link selector
2. Select it and open link selector for edit
3. Make some change, for example change Text to display, and save
Open HTML tab and note that html is not correct, some duplicate content is generated.

**Comment by ElenaGaneva** [comment]
This is not reproducible with latest versions of Sitefinity 11.1+ and latest Firefox
