### ISSUE TITLE
Documents list: User documentation for Documents list

### ISSUE THREAD

**Issue by PepiIvanova** [Sitefinity/feather-widgets#689]
User documentation for Documents list

Sitefinity doc: http://docs.sitefinity.com/download-list-widget

**Comment by NadezhdaPetrova** [comment]
https://github.com/Sitefinity/feather-docs/wiki/Documents-list-widget

**Comment by ElenaGaneva** [comment]
https://docs.sitefinity.com/documents-list-widget-mvc
