### ISSUE TITLE
Navigation: ExcludeTopLevelSibilingPages for local navigation

### ISSUE THREAD

**Issue by rlee2015** [Sitefinity/feather-widgets#780]
In 'All sibling pages of currently opened page' option, missing a define advanced properties to exclude top-level sibling pages (and their child-pages). The value is False (default) or True. 

Configure the navigation view in the followings to create local navigation.
- All sibling pages of currently opened page
- ShowParentPage: True
- ExcludeTopLevelSibilingPages: True

Without this option, we have to create the specific page layouts to display proper navigation links for local navigation.

**Comment by ElenaGaneva** [comment]
Hello rlee2015,

I have been looking into your requirements and I am not sure what is your particular use case. Could you provide me with more details and a simple example what is your page hierarchy and what part of it you want to be displayed in the navigation once you enable the mentioned settings?

Thanks in advance.

Regards,
Elena

**Comment by rlee2015** [comment]
Hi Elena,

Here is the sample site structure.
- Product
  - Web Content Management
     - ASP.NET Form
     - ASP.NET MVC
  - Digital Experience Cloud
- Solutions
- Customers
- Editions
- Resources
- Partners
- Devnet
- About

Configure the navigation view in the followings to create local navigation.
All sibling pages of currently opened page
ShowParentPage: True
ExcludeTopLevelSibilingPages: True

When we access the Web Content Management page, we should see the following in the local navigation. 
- Product
  - Web Content Management
     - ASP.NET Form
     - ASP.NET MVC
  - Digital Experience Cloud

I hope this help. Thanks Elena.

Richard

**Comment by ElenaGaneva** [comment]
Hi Richard,

Thank you for the details. Currently this look can be achieved with the following settings:
-	Set *All sibling pages of currently opened page*
-	Set *Levels to include* to *All*
-	Set *Template* to *Vertical*
-	Set *ShowParentPage* to *True* from the *Advanced*settings

In case these settings doesn’t provide you with the desired behavior please let me know. 

Regards,
Elena

**Comment by rlee2015** [comment]
Hi Elena,

That is the same settings which I have now. Sorry, I got to provide another example to you.

If we clicked the 'Product' page, we should only see 'Product' (and their child-pages) in local navigation however without additional setting for ExcludeTopLevelSiblingPages: true. We will see top level sibling page in the following site structure (vice verse in other top level sibling pages).

- Product
   - Web Content Management
      - ASP.NET Form
      - ASP.NET MVC
   - Digital Experience Cloud
- Solutions
- Customers
- Editions
- Resources
- Partners
- Devnet
- About

Thanks,

Richard

**Comment by ElenaGaneva** [comment]
Hi Richard,

Thank you for the additional info. I have been looking into your scenario and I can suggest you two different approaches for resolving the issue on your side with the Navigation widget.

First you can create hierarchy of page templates to apply different settings for the navigation widget like this:
1. Create two different page templates (from Sitefinity backend->Design->Page Templates). Please note that you can base them on the same parent template.
2. Add navigation widget to the first one with the following settings:
     * Set *All pages under currently opened page*
     * Set *Levels to include* to *All*
     * Set *Template* to *Vertical*
     * Set *ShowParentPage* to *True* from the Advanced settings

Apply this page template to all pages that you have on root level.
3. Add navigation widget to the second template and configure it like this:
     * Set *All sibling pages of currently opened page*
     * Set *Levels to include* to *All*
     * Set *Template* to *Vertical*
     * Set *ShowParentPage* to *True* from the Advanced settings
Apply this template to all pages that are not on root level.

Approach 2:

You can just modify the template of the Navigation widget that you are using. For example if you are using Vertical navigation with Bootstrap package you can edit the file in SitefinityWebApp/RespurcePackages/Bootstrap/MVC/Views/Navigation/NavigationView.Vertical.cshtml  like this:
 
````

@model Telerik.Sitefinity.Frontend.Navigation.Mvc.Models.INavigationModel

@using Telerik.Sitefinity.Frontend.Mvc.Helpers;
@using Telerik.Sitefinity.Frontend.Navigation.Mvc.Models;
@using Telerik.Sitefinity.Modules.Pages;

@*Add scripts and stylesheets*@

<div class="@Model.CssClass">
    @* @Html.Action("GetView", new { viewName = "Dropdown",  model= Model}) *@

      <ul class="nav nav-pills nav-stacked">
        @foreach (var node in Model.Nodes)
        {
			if(node.IsCurrentlyOpened || node.HasChildOpen)
			{
				@RenderSubLevelsRecursive(node);
			}
        }
    </ul>
</div>

@*Here is specified the rendering for the sub levels*@
@helper RenderSubLevelsRecursive(NodeViewModel node)
....

````

 I have added extra if clause for the root level nodes so they can render depending on your requirements.

Please let me know if this suits you better. 


Regards,
Elena

**Comment by rlee2015** [comment]
Hi Elena,

Thanks for your suggestions. Based on above information, you gave me a new idea to create a custom view using sitemap template. 

I modified the extra if clause for the root level nodes (including custom CSS classes) so they can render depending on our requirements.

@model Telerik.Sitefinity.Frontend.Navigation.Mvc.Models.INavigationModel
@using Telerik.Sitefinity.Frontend.Mvc.Helpers;
@using Telerik.Sitefinity.Frontend.Navigation.Mvc.Models;
@using Telerik.Sitefinity.Modules.Pages;
<div class="@Model.CssClass">
    @* @Html.Action("GetView", new { viewName = "Dropdown",  model= Model}) *@
    @foreach (var node in Model.Nodes)
    {
        if ((node.IsCurrentlyOpened || node.HasChildOpen) & (node.ChildNodes.Count >= 1))
        {
            @RenderRootLevelNode(node);
        }
    }
</div>

Here are settings for the widget.
* Set Top-level pages (and their child-pages if template allows)
* Set Levels to include to All
* Set Template to custom template
* Set ShowParentPage to True from the Advanced settings

Thanks and you can close this issue.

Richard
