### ISSUE TITLE
Register widget form action url with multiple languages enabled is wonky

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather-widgets#820]
What's up with this?

<form action="/~/https:/www.outbreakhelp.ca/register/Index" method="POST" name="defaultForm">  

https://www.outbreakhelp.ca/register

Seemed to start when I added french as a 2nd language

Can anyone reproduce?

**Comment by Boyko-Karadzhov** [comment]
Hello Steve,

What are you experiencing? I can see a register form. Should I try to register? What should I expect?

Thanks,
Boyko

**Comment by sitefinitysteve** [comment]
You can expect it to work, because I worked around the issue...let me lay it out for you

1) Reg form wasn't working initally...would post back to /register/index and not create the user
2) Fix was that IIS rewrite was changing "Index" to "index" and Sitefinity wasn't picking that up, so I added a rewrite ignore for HttpPost
3) On live I then enabled a second language.
4) The registration url then changed from action="/registration/Index" to "/~/http://www.outbreakhelp.ca/registration/Index" which obviously fails
5) I used the SF source code for 8.0.5700 to debug the HybridForm.cs and...it rendered out just fine.
6) Realized that I was on 5704 and in 5703 they made some changes to BeginFormSitefinity.  Putting that code into the source did indeed show the gimped action url.

Video: http://screencast.com/t/X3zpgFch6r


The Fix (which is now on live as well) was to just NOT use BeginFormsSitefinity but instead use the native BeginForm instead.

So this fixed both issues
1) It just posts back to itself, not /Index (in the url)
2) ...and it creates the user

So really the problem is with whoever manages "BeginFormsSitefinity"

**Comment by sitefinitysteve** [comment]
More details in ticket http://www.telerik.com/account/support-tickets/view-ticket.aspx?threadid=927372

...but basically the video shows what's up

**Comment by sitefinitysteve** [comment]
This borks the Profile widget too, it's unusable

**Comment by Boyko-Karadzhov** [comment]
Hello Steve,

Thanks for reporting. This is a regression in the HybridForm from one of the internal builds. There is a fix waiting to be released and probably you will be able to get it in the next internal release.

Regards,
Boyko

**Comment by mariushm** [comment]
Fix was included in 8.0.5712, closing this one.
