### ISSUE TITLE
Content Block: Make widget editable on pages missing

### ISSUE THREAD

**Issue by PeterMarinov** [Sitefinity/feather-widgets#844]
Because the content block has custom action commands one has forgot to add the make editable on pages option available with the web forms ContentBlock widget.

We should add it to the option available for the Content Block MVC widget

**Comment by PepiIvanova** [comment]
A little bit of clarification:
1. D&D MVC Content block widget  in a template
2. Expand More menu
Result: "Make editable on pages" option is missing
