### ISSUE TITLE
Registration Widget Localization

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather-widgets#858]
1) Registration Widget doesn't send the confirmation email in the current language
2) Confirmation Page not specified in the emails second language.  So this is the link it sent me "?user=df37fc73-5887-6d8b-9e8a-ff00003a1412&provider=Default" ...no prefix with the site or activation page.

This is what happens in english
https://www.outbreakhelp.ca/register/activation?user=a937fc73-5887-6d8b-XXXX-ff00003aXXXX&provider=Default

French is just
?user=a937fc73-5887-6d8b-XXXX-ff00003aXXXX&provider=Default

**Comment by dzhenko** [comment]
Hey Steve,

By default, the confirmation email is not translated to the current language. You can easily achieve that by setting a different (translated) "Confirmation email template" when setting up your registration widget.

When you translate a page which has an registration widget, you have to set the Activation Page even if the page is copied from another language.

If you still reproduce this issue when you explicitly set the Activation Page on your translated page, provide us with more info about the current settings of the widget.

Kind Regards,
Dzhenko

**Comment by sitefinitysteve** [comment]
Oh I see...the feather widget doesn't yet have the ability to edit\create templates.  I had to make a webforms page and drop on the old webforms widget to edit\create templates, thanks! ...just gonna test this

**Comment by sitefinitysteve** [comment]
So what do we do here, should I open a new issue to create\edit templates or it's in the backlog somewhere and I should just close this?

**Comment by mariushm** [comment]
Hi Steve,

We've registered this as incomplete functionality in our backlog and will include it in some of our upcoming releases, so you can close this one without the need for a new one.

Mariush
