### ISSUE TITLE
Content Block Selector Needed

### ISSUE THREAD

**Issue by morphosic** [Sitefinity/feather-widgets#913]
A selector is needed to pick an existing content block to display. Currently the blocks guid must be looked up in the db to be able to reference an existing block.

**Comment by ElenaGaneva** [comment]
Hi morphosic,

The MVC Content Block widget that comes with Feather provides the functionality to select from existing content block item. You can take advantage of this functionality by dragging the ContentBlock on your page or template and choosing More->Use shared from the upper right corner of the widget:
![cbuseshared](https://cloud.githubusercontent.com/assets/6451115/7427792/e2c00ef0-efeb-11e4-91a1-ef4ea41b47d8.PNG)

Regards,
Elena

**Comment by morphosic** [comment]
awesome, thanks! is this in the documentation?
