### ISSUE TITLE
ChangePassword is missing password recovery functionality

### ISSUE THREAD

**Issue by sitefinitysteve** [Sitefinity/feather-widgets#950]
User gets emailed their PW, but clicking the link sends you to a page telling you that you must be logged in to change your PW.

You can see the controller action just checks if the user is authenticated, doesn't check for the querystring key

**Comment by Boyko-Karadzhov** [comment]
Hello Steve,

ChangePassword just enables a user to change his/her password while logged in. Password reset is handled by the LoginForm. In password recovery scenario the user is expected to use the password and log on as usual using the LoginForm.

Let me know if this is you have any issues configuring the LoginForm or this isn't what you need.

Regards,
Boyko

**Comment by sitefinitysteve** [comment]
Okay so maybe the issue is that I needed to use the githib sts social login widget, and in webforms you need to pick the page that contains the "Change Password" widget because that's the place the user gets directed in the recovery email.

...so this is just different in feather then?

Steve

**Comment by Boyko-Karadzhov** [comment]
Yes. Password reset happens in the login form in Feather. The WebForms login will send a mail with link to the 'change password' page and the login form from Feather sends a URL to itself. 

Is this ok for you? Let me know if this leaves any unresolved issues.
