### ISSUE TITLE
jQuery loading more than once

### ISSUE THREAD

**Issue by rlee2015** [Sitefinity/feather-widgets#974]
Environment: Feather 1.2.200.1 and Sitefinity 8.0.5710.0.

I created a page adding SearchBox and Navigation (Horizontal) widgets. I found jQuery loading twice (one is in WebResource.axd and the other one is in ScriptResource.axd).

Could you please ensure only loading jQuery once for any widgets within a page?

Thanks,

Richard

**Comment by mariushm** [comment]
Hi Robert,

Thanks, this is a bug in Search Box when inline editing is disabled. We will fix it for next release.

Mariush
